### ISSUE TITLE
Configure TFS2010 build

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#115] opened 2012-08-28 14:19 UTC
To adhere to City Index internal development standards, the projects need to be built under TFS2010.

We need a way to import the GitHub projects into TFS (perhaps http://gittf.codeplex.com/)

The TFS builds should generate the same packages as the Jenkins build, so that packages created with TFS can be installed using the existing Installation Guides

**Comment by mrdavidlaing** [comment] 2012-08-28 14:22
I have created a TFS2010 + VS2010 server in the AWS-labs-EU-west environment named: 
`TFS2010 (46.51.176.50)   i-c5e2df8d` with Elastic IP `46.51.176.50`

This m1.large machine should be left in the stopped state when not in use.  Start it via the EC2 Web console, and don't forget to reassign the correct Elastic IP.

Login credentials can be obtains from the Credentials tag

The screenshot below shows how TFS has initially been configured:

<img src="https://dl.dropbox.com/u/33609233/CIAPI/CIAPI_latency_collector_TFS_build_layout.png" />
1. The GitHub projects have been cloned to `C:\Dev\GitHub`.  
2. Mirror TFS projects have been setup, with their workspaces checked out to `C:\Dev\TFS\CIAPI_Latency_Collector`
3. 2 TFS builds have been created, which attempt to build the AppMetrics & CIAPILatencyCollector projects.

**Comment by fandrei** [comment] 2012-09-03 08:38
I don't understand completely, how this works together. Does it pull changes from Git on every build?
The first problem I've found is that some files can't be updated during build because of  read-only attribute (probably set by TFS). Should we checkout this files before build, or just reset read-only attribute?

**Comment by mrdavidlaing** [comment] 2012-09-03 09:50
Currently we have no automated process for moving from GitHub to TFS.  To begin with, I don't think we need an automated one; just a defined manual process that we can follow should be fine for now.

Our options are:
1.  Completely manual - _looses_ Git commit history - done once / production release
   1.  `git pull` into the `C:\Dev\GitHub` locations.
   2.  TFS Checkout to the `C:\Dev\TFS` locations (must let TFS remove readonly attrib, or it gets confused)
   3.  Copy from  `C:\Dev\GitHub` => `C:\Dev\TFS`
   4.  TFS Checkin, triggers TFS build.
2.  [Git-TF](http://gittf.codeplex.com/) driven - _retains_ Git commit history - done once / production release
   1.  `git pull` into the `C:\Dev\GitHub` locations.
   2.  `git tf checkin` from `C:\Dev\GitHub` locations into TFS, triggers TFS build.

I'll leave you to choose which one has the right "easy to implement / most elegant" balance.

In both cases we need a TFS build script that will build the same set of output packages as the Jenkins build script.

**Comment by fandrei** [comment] 2012-09-04 08:20
Not sure about Git-Tf; when I'm trying to use it, getting this error message:
git-tf: User config file C:\Users\Administrator.gitconfig invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file C:\Users\Administrator.gitconfig
UPD if it says file is invalid, probably this is due to Git updated config file format

Anyway, according to the documentation http://download.microsoft.com/download/A/E/2/AE23B059-5727-445B-91CC-15B7A078A7F4/Git-TF_GettingStarted.html, Git history won't be transferred to TFS.
So I'll try to stick to the first approach.
However, the problem here is how to deal with added/deleted files.

**Comment by mrdavidlaing** [comment] 2012-09-04 09:12
Agree with your analysis.

Concerning dealing with deleted files - how about doing the copy step using a merge tool like win-merge.  Or a windows rsync clone.

**Comment by fandrei** [comment] 2012-09-06 05:30
Solved the problem with Git-TF, it was due to config file encoding (only ANSI is accepted)

Q: we need to run only build, or full build-and-test suite? If second option, where to setup web applications?

**Comment by mrdavidlaing** [comment] 2012-09-07 08:36
Just run the build + unit tests.  Don't run the integration tests.

**Comment by fandrei** [comment] 2012-09-13 10:37
Build is successful. Now I need to fix unit tests.
I put git-tf update script here: C:\Dev\update.bat

**Comment by mrdavidlaing** [comment] 2012-09-13 12:22
:+1:  Go you!

**Comment by fandrei** [comment] 2012-09-26 08:44
Unit tests are working now, but I'm struggling with OpenCover. It gives this error, when running in the TFS system:

No results - no assemblies that matched the supplied filter were instrumented this could be due to missing PDBs for the assemblies that match the filter please review the output file and refer to the Usage guide (Usage.rtf)

All PDBs are present and up-to-date. Have you ever had such error?

**Comment by mrdavidlaing** [comment] 2012-09-26 15:27
I vote for not including OpenCover in the TFS build for now.

**Comment by fandrei** [comment] 2012-09-27 07:57
Maybe we can keep it as it is now (OpenCover is running, but not generating any results).

I've found, that the problem is somewhat related to type filtering. With filter

```
"-filter:+[*]*"
```

 it works, but when some type exclusions are added (for CassiniDev, etc)

```
"-filter:+[*]* -[Test*]* -[ApiGeoIP*]* -[CassiniDev*]*"
```

 OpenCover doesn't work on TFS machine correctly. But exactly the same parameters are working on Jenkins and my local machine. Weird.

**Closed as completed** 2012-10-02 10:22 UTC

**Comment by fandrei** [comment] 2012-10-02 10:29
Software setup:

install Java (required for git-tf); add to the PATH variable
install git-tf; add to the path
install WiX
apply SP1 to VS2010 (was required after WiX installation)

PS copy update script C:\Dev\update.bat to the target machine
